import fs from 'node:fs'
import path from 'node:path'

import type { Plugin, ResolvedConfig } from 'vite'

// Internal Vite virtual module id.
// We dynamically generate this module from the compiled contract sources map
// so the frontend can import them like a normal ES module.
const SIMPLICITY_SOURCES_VIRTUAL = '\0virtual:simplicity-sources'
const SIMPLICITY_SOURCES_ID = 'virtual:simplicity-sources'

interface SimplicitySourcesPluginOptions {
  // Path to the `metadata.json` artifact generated by `simplex build` in crates/contracts
  // (committed under crates/contracts/src/artifacts/metadata.json).
  sourcesPath: string
}

interface SimplicityMetadata {
  sources: Record<string, { cmr: string; content: string }>
}

function toShortName(fileName: string): string {
  return fileName.replace(/\.simf$/, '')
}

export function simplicitySourcesPlugin(options: SimplicitySourcesPluginOptions): Plugin {
  let viteConfig: ResolvedConfig
  let resolvedSourcesPath: string

  function readSources(): Record<string, string> {
    if (!fs.existsSync(resolvedSourcesPath)) {
      throw new Error(
        `Simplicity contract metadata not found: ${resolvedSourcesPath}\n` +
          'Generate it with `simplex build` in crates/contracts.',
      )
    }

    const raw = fs.readFileSync(resolvedSourcesPath, 'utf-8')
    const metadata = JSON.parse(raw) as SimplicityMetadata

    return Object.fromEntries(
      Object.entries(metadata.sources).map(([fileName, { content }]) => [
        toShortName(fileName),
        content,
      ]),
    )
  }

  return {
    name: 'simplicity-sources',

    configResolved(config) {
      viteConfig = config
      resolvedSourcesPath = path.resolve(viteConfig.root, options.sourcesPath)
    },

    resolveId(id) {
      if (id === SIMPLICITY_SOURCES_ID) {
        return SIMPLICITY_SOURCES_VIRTUAL
      }

      return null
    },

    load(id) {
      if (id !== SIMPLICITY_SOURCES_VIRTUAL) {
        return null
      }

      // Re-run this hook whenever contract_sources.json changes, so `pnpm dev`
      // picks up freshly exported contract sources without a manual restart.
      this.addWatchFile(resolvedSourcesPath)

      const sources = readSources()

      return `export const sources = ${JSON.stringify(sources)}`
    },
  }
}
