import fs from 'node:fs'
import path from 'node:path'

import type { Plugin, ResolvedConfig } from 'vite'

// Internal Vite virtual module id.
// We dynamically generate this module from the compiled contract sources map
// so the frontend can import them like a normal ES module.
const SIMPLICITY_SOURCES_VIRTUAL = '\0virtual:simplicity-sources'
const SIMPLICITY_SOURCES_ID = 'virtual:simplicity-sources'

interface SimplicitySourcesPluginOptions {
  // Path to the `contract_sources.json` map generated by
  // `cargo run -p lending-contracts --example export_contract_sources`.
  sourcesPath: string
}

export function simplicitySourcesPlugin(options: SimplicitySourcesPluginOptions): Plugin {
  let viteConfig: ResolvedConfig
  let resolvedSourcesPath: string

  function readSources(): Record<string, string> {
    if (!fs.existsSync(resolvedSourcesPath)) {
      throw new Error(
        `Simplicity contract sources not found: ${resolvedSourcesPath}\n` +
          'Generate it with `cargo run -p lending-contracts --example export_contract_sources` in crates/contracts.',
      )
    }

    const raw = fs.readFileSync(resolvedSourcesPath, 'utf-8')

    return JSON.parse(raw) as Record<string, string>
  }

  return {
    name: 'simplicity-sources',

    configResolved(config) {
      viteConfig = config
      resolvedSourcesPath = path.resolve(viteConfig.root, options.sourcesPath)
    },

    resolveId(id) {
      if (id === SIMPLICITY_SOURCES_ID) {
        return SIMPLICITY_SOURCES_VIRTUAL
      }

      return null
    },

    load(id) {
      if (id !== SIMPLICITY_SOURCES_VIRTUAL) {
        return null
      }

      // Re-run this hook whenever contract_sources.json changes, so `pnpm dev`
      // picks up freshly exported contract sources without a manual restart.
      this.addWatchFile(resolvedSourcesPath)

      const sources = readSources()

      return `export const sources = ${JSON.stringify(sources)}`
    },
  }
}
