ALTER TYPE utxo_type ADD VALUE IF NOT EXISTS 'lender_vault';
ALTER TYPE utxo_type ADD VALUE IF NOT EXISTS 'protocol_fee_vault';

CREATE TYPE vault_type AS ENUM ('lender', 'protocol_fee');

CREATE TABLE offer_vaults (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    offer_id BIGINT NOT NULL REFERENCES offers(id) ON DELETE CASCADE,
    vault_type vault_type NOT NULL,

    txid BYTEA NOT NULL,
    vout INTEGER NOT NULL,
    amount BIGINT NOT NULL,
    already_supplied BIGINT NOT NULL,
    is_finalized BOOLEAN NOT NULL DEFAULT false,

    created_at_height BIGINT NOT NULL,
    updated_at_height BIGINT NOT NULL,

    spent_txid BYTEA,
    spent_at_height BIGINT,

    UNIQUE (txid, vout)
);

-- At most one active vault of each type per offer at any given time.
CREATE UNIQUE INDEX idx_offer_vaults_active_per_type
ON offer_vaults (offer_id, vault_type)
WHERE spent_txid IS NULL;
