indexer:
  base_url: 'http://127.0.0.1:8000'

esplora:
  base_url: 'https://liquid.network/liquidtestnet/api'
  network: 'liquidtestnet'

schedule:
  interval_secs: 86400

harvest:
  min_vaults_per_tx: 5
  max_vaults_per_tx: 25

principal_asset: '38fca2d939696061a8f76d4e6b5eecd54e3b4221c846f24a6b279e79952850a5'
