application:
  port: 8000
  cors:
    allowed_origins:
      - "*"
database:
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "lending-indexer"
esplora:
  base_url: "https://blockstream.info/liquidtestnet/api"
  timeout: 10
indexer:
  interval: 10000
  last_indexed_height: 2342450
